// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmqyc_5xqkzPL7GLUJjlF_Ytc4bpNLUyI',
    appId: '1:156201934558:web:855b78c2734224d20c2c4f',
    messagingSenderId: '156201934558',
    projectId: 'expense-two',
    authDomain: 'expense-two.firebaseapp.com',
    storageBucket: 'expense-two.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLcPpVSofgaC2SUXfP4kHEvU1ilFdUw_M',
    appId: '1:156201934558:android:35b32885e6ff98d80c2c4f',
    messagingSenderId: '156201934558',
    projectId: 'expense-two',
    storageBucket: 'expense-two.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgUNelIaZyeaoBL6l41RRYp1pzTaq-uV0',
    appId: '1:156201934558:ios:a7e180a5986154da0c2c4f',
    messagingSenderId: '156201934558',
    projectId: 'expense-two',
    storageBucket: 'expense-two.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgUNelIaZyeaoBL6l41RRYp1pzTaq-uV0',
    appId: '1:156201934558:ios:a7e180a5986154da0c2c4f',
    messagingSenderId: '156201934558',
    projectId: 'expense-two',
    storageBucket: 'expense-two.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmqyc_5xqkzPL7GLUJjlF_Ytc4bpNLUyI',
    appId: '1:156201934558:web:3970269028881ed30c2c4f',
    messagingSenderId: '156201934558',
    projectId: 'expense-two',
    authDomain: 'expense-two.firebaseapp.com',
    storageBucket: 'expense-two.appspot.com',
  );
}
